# Generated by Django 2.2 on 2021-01-05 00:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(max_length=40)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Gldetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glnum', models.CharField(max_length=12, validators=[django.core.validators.MinLengthValidator(12)], verbose_name='GL Number')),
                ('gldesc', models.CharField(max_length=40, verbose_name='GL Description')),
                ('glamt', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='GL Amount')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='rec.Entity')),
            ],
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=7, validators=[django.core.validators.MinLengthValidator(7)])),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Glpost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jdate', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Date')),
                ('jref', models.CharField(max_length=6, validators=[django.core.validators.MinLengthValidator(6)], verbose_name='Reference')),
                ('jamt', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Amount')),
                ('jdesc', models.CharField(max_length=20, verbose_name='Description')),
                ('jattach', models.FileField(blank=True, default=None, null=True, upload_to='documents/', verbose_name='Backup Attachment')),
                ('gldetail', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='rec.Gldetail')),
            ],
        ),
        migrations.AddField(
            model_name='gldetail',
            name='period',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='rec.Period'),
        ),
        migrations.AddField(
            model_name='gldetail',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rec.Status'),
        ),
        migrations.AddField(
            model_name='gldetail',
            name='username',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='usernames', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='gldetail',
            unique_together={('entity', 'period', 'glnum')},
        ),
    ]
